---
title: "Wading Birds"
code-fold: true
---

Focus on wading birds.


```{r setup}
library(here)
```

```{r}
#| code-summary: load data
source("../R/loadData.R")
df <- loadData()
```

```{r}
#| code-summary: constants
ES_NUMBER <- 10
HEX_RES <- 13

# Declare a list of species names to filter
# TODO: fix this list
SPECIES_LIST <- c("Canada Goose", "Osprey", "Bald Eagle", "Blue Jay")
```


```{r}
#| code-summary: reduce to selected species only

# Subset the dataframe using the species list
filtered_df <- df[df$species %in% SPECIES_LIST, ]
```

```{R}
#| code-summary: heatmap of points
# create a plot showing a heatmap from the points
library('ggplot2')
library('maps')
mapBoundLat <- c(-83, -82)
mapBoundLon <- c(27.5, 28.5)
ggplot(data = filtered_df, aes(x = decimalLongitude, y = decimalLatitude)) +
  borders("world", colour = "gray50", fill = "gray90") +
  stat_density_2d(
    aes(fill = after_stat(level)), 
    geom = "polygon", 
    alpha = 0.1, 
    bins=10,
    n=2000,
    adjust = 2  # Increase bandwidth for smoother contours
  ) +
  scale_fill_viridis_c() +
  coord_quickmap(xlim = mapBoundLat, ylim = mapBoundLon) +
  theme_minimal() +
  labs(x = "Longitude", y = "Latitude", 
       title = "Heat Map of GBIF Observations in Tampa Bay Area",
       fill = "Density")
```

```{r}
#| code-summary: use function to calc & plot indicators
#| message: false
#| warning: false
source(here("R/gmap_indicator.R"))
source(here("R/df2grid.R"))
grid <- df2grid(filtered_df, HEX_RES, ES_NUMBER)

gmap_indicator(grid, "es", label = "es")
gmap_indicator(grid, "shannon", label = "shannon")
gmap_indicator(grid, "simpson", label = "simpson")
gmap_indicator(grid, "n", label = "n")

```