project:
  type: website

website:
  title: "gbi-page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - richness.qmd
      - text: Habitat-specific
        menu:
        - habitats/wading.qmd
      - text: Source Code on GitHub
        href: https://github.com/BeakGeeks/gbi-page
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



