---
title: "gbi-page"
code-fold: true
---

Below is an overview of the points from GBIF.

```{r}
#| code-summary: load data
source("R/loadData.R")
df <- loadData()
```


```{R}
#| code-summary: constants
mapBoundLat <- c(-83, -82)
mapBoundLon <- c(27.5, 28.5)
```

```{R}
#| code-summary: basic map of points
library('ggplot2')
library('maps')
ggplot(data = df, aes(x = decimalLongitude, y = decimalLatitude)) +
  borders("world", colour = "gray50", fill = "gray90") +
  geom_point(color = "red", size = 3) +
  coord_quickmap(xlim = mapBoundLat, ylim = mapBoundLon) +
  theme_minimal() +
  labs(x = "Longitude", y = "Latitude", title = "GBIF Observations in Tampa Bay Area")
```

```{R}
#| code-summary: heatmap of points
# create a plot showing a heatmap from the points
library('ggplot2')
library('maps')
ggplot(data = df, aes(x = decimalLongitude, y = decimalLatitude)) +
  borders("world", colour = "gray50", fill = "gray90") +
  stat_density_2d(
    aes(fill = after_stat(level)), 
    geom = "polygon", 
    alpha = 0.1, 
    bins=10,
    n=2000,
    adjust = 2  # Increase bandwidth for smoother contours
  ) +
  scale_fill_viridis_c() +
  coord_quickmap(xlim = mapBoundLat, ylim = mapBoundLon) +
  theme_minimal() +
  labs(x = "Longitude", y = "Latitude", 
       title = "Heat Map of GBIF Observations in Tampa Bay Area",
       fill = "Density")
```

```{R}
#| code-summary: heatmap w/ hexes

library(ggplot2)
#library(hexbin)

ggplot(data = df, aes(x = decimalLongitude, y = decimalLatitude)) +
  borders("world", colour = "gray50", fill = "gray90") +
  geom_hex(bins = 5000) +  # Adjust 'bins' for resolution
  scale_fill_viridis_c(alpha=0.5) +
  coord_quickmap(xlim = mapBoundLat, ylim = mapBoundLon) +
  theme_minimal() +
  labs(x = "Longitude", y = "Latitude", 
       title = "Hexbin Density Plot of GBIF Bird Observations in Tampa Bay Area",
       fill = "N Records")
```
```{r}
#| code-summary: heatmap with leaflet

library(leaflet)
library(leaflet.extras)
library(dplyr)

# Generate a leaflet map with a heatmap layer
leaflet(df) %>%
  addTiles() %>%
  addHeatmap(
    lng = ~decimalLongitude, lat = ~decimalLatitude,
    intensity = ~10, radius = 10, blur = 20, max = 0.05
  )

```
